<!doctype html><html lang=en-uk><head><script data-goatcounter=https://ruivieira-dev.goatcounter.com/count async src=//gc.zgo.at/count.js></script>
<script src=https://unpkg.com/@alpinejs/intersect@3.x.x/dist/cdn.min.js></script>
<script src=https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js></script>
<script type=module src=https://ruivieira.dev/js/deeplinks/deeplinks.js></script>
<link rel=preload href=https://ruivieira.dev/lib/fonts/fa-brands-400.woff2 as=font type=font/woff2 crossorigin=anonymous><link rel=preload href=https://ruivieira.dev/lib/fonts/fa-regular-400.woff2 as=font type=font/woff2 crossorigin=anonymous><link rel=preload href=https://ruivieira.dev/lib/fonts/fa-solid-900.woff2 as=font type=font/woff2 crossorigin=anonymous><link rel=preload href=https://ruivieira.dev/fonts/firacode/FiraCode-Regular.woff2 as=font type=font/woff2 crossorigin=anonymous><link rel=preload href=https://ruivieira.dev/fonts/vollkorn/Vollkorn-Regular.woff2 as=font type=font/woff2 crossorigin=anonymous><link rel=stylesheet href=https://ruivieira.dev/css/kbd.css type=text/css><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><title>Exception Bubbling in Python Â· Rui Vieira</title><link rel=canonical href=https://ruivieira.dev/blog/2023-09-02.html><meta name=viewport content="width=device-width,initial-scale=1"><meta name=robots content="all,follow"><meta name=googlebot content="index,follow,snippet,archive"><meta property="og:title" content="Exception Bubbling in Python"><meta property="og:description" content="One aspect of Java that occasionally nudges at me is its explicit approach to exception handling. Java requires developers to either handle exceptions via try-catch blocks or declare them in method signatures. While it does enforce robustness, it sometimes feels a bit too constrained, especially when compared to the flexible nature of Python.
Recently, I crafted a solution in Python for k8sutils. Instead of the usual explicit exception handling or modifying method signatures, I created a Python decorator - akin to annotations in Java - that substitutes an exception for another without altering the underlying code."><meta property="og:type" content="article"><meta property="og:url" content="https://ruivieira.dev/blog/2023-09-02.html"><meta property="article:section" content="blog"><meta property="article:published_time" content="2023-09-02T00:00:00+00:00"><meta property="article:modified_time" content="2023-10-01T20:46:29+01:00"><meta name=twitter:card content="summary"><meta name=twitter:title content="Exception Bubbling in Python"><meta name=twitter:description content="One aspect of Java that occasionally nudges at me is its explicit approach to exception handling. Java requires developers to either handle exceptions via try-catch blocks or declare them in method signatures. While it does enforce robustness, it sometimes feels a bit too constrained, especially when compared to the flexible nature of Python.
Recently, I crafted a solution in Python for k8sutils. Instead of the usual explicit exception handling or modifying method signatures, I created a Python decorator - akin to annotations in Java - that substitutes an exception for another without altering the underlying code."><link rel=stylesheet href=https://ruivieira.dev/css/styles.css><!--[if lt IE 9]><script src=https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js></script>
<script src=https://oss.maxcdn.com/respond/1.4.2/respond.min.js></script><![endif]--><link rel=icon type=image/png href=https://ruivieira.dev/images/favicon.ico></head><body class="max-width mx-auto px3 ltr"><div class="content index py4"><header id=header><a href=https://ruivieira.dev><div id=logo style=background-image:url(https://ruivieira.dev/images/logo.png)></div><div id=title><h1>Rui Vieira</h1></div></a><div id=nav><ul><li class=icon><a href=# aria-label=Menu><i class="fas fa-eye fa-2x" aria-hidden=true></i></a></li><li><a href=https://ruivieira.dev/>Home</a></li><li><a href=https://ruivieira.dev/blog/>Blog</a></li><li><a href=https://ruivieira.dev/draw/>Drawings</a></li><li><a href=https://ruivieira.dev/map/>All pages</a></li><li><a href=https://ruivieira.dev/search.html>Search</a></li></ul></div></header><h1>2023-09-02</h1><h3>Exception Bubbling in Python</h3><p><p>One aspect of <a href=https://ruivieira.dev/java.html>Java</a> that occasionally nudges at me is its explicit approach to exception handling.
Java requires developers to either handle exceptions via <code>try-catch</code> blocks or declare them in method signatures. While it does enforce robustness, it sometimes feels a bit too constrained, especially when compared to the flexible nature of Python.</p><p>Recently, I crafted a solution in Python for <a href=https://github.com/ruivieira/k8s.py>k8sutils</a>.
Instead of the usual explicit exception handling or modifying method signatures, I created a <a href=https://ruivieira.dev/python.html>Python</a> decorator - akin to annotations in Java - that substitutes an exception for another without altering the underlying code. Here&rsquo;s what it looks like:</p><div class=highlight><pre tabindex=0 style=background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span><span style=font-weight:700>import</span> <span style=color:#555>functools</span>
</span></span><span style=display:flex><span><span style=font-weight:700>import</span> <span style=color:#555>subprocess</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=font-weight:700>def</span> <span style=color:#900;font-weight:700>rethrow</span>(exception_type<span style=font-weight:700>=</span><span style=color:#900;font-weight:700>Exception</span>):
</span></span><span style=display:flex><span>    <span style=color:#b84>&#34;&#34;&#34;Rethrow a CalledProcessError as the specified exception type.&#34;&#34;&#34;</span>
</span></span><span style=display:flex><span>    
</span></span><span style=display:flex><span>    <span style=font-weight:700>def</span> <span style=color:#900;font-weight:700>decorator</span>(func):
</span></span><span style=display:flex><span>        @functools.wraps(func)
</span></span><span style=display:flex><span>        <span style=font-weight:700>def</span> <span style=color:#900;font-weight:700>wrapper</span>(<span style=font-weight:700>*</span>args, <span style=font-weight:700>**</span>kwargs):
</span></span><span style=display:flex><span>            <span style=font-weight:700>try</span>:
</span></span><span style=display:flex><span>                <span style=font-weight:700>return</span> func(<span style=font-weight:700>*</span>args, <span style=font-weight:700>**</span>kwargs)
</span></span><span style=display:flex><span>            <span style=font-weight:700>except</span> subprocess<span style=font-weight:700>.</span>CalledProcessError <span style=font-weight:700>as</span> e:
</span></span><span style=display:flex><span>                <span style=font-weight:700>raise</span> exception_type(<span style=color:#b84>f</span><span style=color:#b84>&#34;Command failed: </span><span style=color:#b84>{</span>e<span style=font-weight:700>.</span>cmd<span style=color:#b84>}</span><span style=color:#b84>. Error: </span><span style=color:#b84>{</span>e<span style=font-weight:700>.</span>output<span style=color:#b84>}</span><span style=color:#b84>&#34;</span>) <span style=font-weight:700>from</span> <span style=color:#555>e</span>
</span></span><span style=display:flex><span>        <span style=font-weight:700>return</span> wrapper
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>    <span style=font-weight:700>return</span> decorator
</span></span></code></pre></div><p>Using this decorator, it becomes straightforward to alter the exception being thrown:</p><div class=highlight><pre tabindex=0 style=background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span>@rethrow(<span style=color:#900;font-weight:700>ValueError</span>)
</span></span><span style=display:flex><span><span style=font-weight:700>def</span> <span style=color:#900;font-weight:700>get</span>(namespace<span style=font-weight:700>=</span><span style=font-weight:700>None</span>):
</span></span><span style=display:flex><span>    <span style=color:#b84>&#34;&#34;&#34;Get all deployments in the cluster.&#34;&#34;&#34;</span>
</span></span><span style=display:flex><span>    cmd <span style=font-weight:700>=</span> <span style=color:#b84>&#34;kubectl get deployments -o json&#34;</span>
</span></span><span style=display:flex><span>    <span style=font-weight:700>if</span> namespace:
</span></span><span style=display:flex><span>        cmd <span style=font-weight:700>+=</span> <span style=color:#b84>f</span><span style=color:#b84>&#34; -n </span><span style=color:#b84>{</span>namespace<span style=color:#b84>}</span><span style=color:#b84>&#34;</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>    result <span style=font-weight:700>=</span> subprocess<span style=font-weight:700>.</span>run(cmd, shell<span style=font-weight:700>=</span><span style=font-weight:700>True</span>, check<span style=font-weight:700>=</span><span style=font-weight:700>True</span>, capture_output<span style=font-weight:700>=</span><span style=font-weight:700>True</span>, text<span style=font-weight:700>=</span><span style=font-weight:700>True</span>)
</span></span><span style=display:flex><span>    deployments <span style=font-weight:700>=</span> json<span style=font-weight:700>.</span>loads(result<span style=font-weight:700>.</span>stdout)
</span></span><span style=display:flex><span>    <span style=font-weight:700>return</span> deployments
</span></span></code></pre></div><p>The <code>@rethrow(ValueError)</code> decorator automatically translates a <code>CalledProcessError</code> to a <code>ValueError</code> without the need to change the method&rsquo;s code.</p><p>For another example:</p><div class=highlight><pre tabindex=0 style=background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-python data-lang=python><span style=display:flex><span>@rethrow(<span style=color:#900;font-weight:700>RuntimeError</span>)
</span></span><span style=display:flex><span><span style=font-weight:700>def</span> <span style=color:#900;font-weight:700>delete_deployment</span>(deployment_name):
</span></span><span style=display:flex><span>    <span style=color:#b84>&#34;&#34;&#34;Delete a specific deployment.&#34;&#34;&#34;</span>
</span></span><span style=display:flex><span>    cmd <span style=font-weight:700>=</span> <span style=color:#b84>f</span><span style=color:#b84>&#34;kubectl delete deployment </span><span style=color:#b84>{</span>deployment_name<span style=color:#b84>}</span><span style=color:#b84>&#34;</span>
</span></span><span style=display:flex><span>    subprocess<span style=font-weight:700>.</span>run(cmd, shell<span style=font-weight:700>=</span><span style=font-weight:700>True</span>, check<span style=font-weight:700>=</span><span style=font-weight:700>True</span>)
</span></span></code></pre></div><p>Here, instead of bubbling up the generic <code>CalledProcessError</code>, any error encountered will raise a <code>RuntimeError</code>.</p></p><footer id=footer><div class=footer-left>Copyright &copy; 2023 Rui Vieira</div><div class=footer-right><nav><ul><li><a href=https://ruivieira.dev/>Home</a></li><li><a href=https://ruivieira.dev/blog/>Blog</a></li><li><a href=https://ruivieira.dev/draw/>Drawings</a></li><li><a href=https://ruivieira.dev/map/>All pages</a></li><li><a href=https://ruivieira.dev/search.html>Search</a></li></ul></nav></div></footer></div></body><link rel=stylesheet href=https://ruivieira.dev/css/fa.min.css><script src=https://ruivieira.dev/js/jquery-3.6.0.min.js></script>
<script src=https://ruivieira.dev/js/mark.min.js></script>
<script src=https://ruivieira.dev/js/main.js></script></html>